---
title: "Jingyi_Zuo"
format: html
---

# Task 1 
```{r}
pre_treatment <- c (130, 128, 116, 124, 133, 134, 118, 126, 114, 127, 141, 138, 128, 140, 137, 131, 120, 128, 139, 135)
after_treatment <- c(114, 98, 113, 99, 107, 116, 113, 111, 119, 117, 101, 119, 130, 122, 106, 106, 124, 102, 117, 113)
names(pre_treatment) <- paste("Subject", 1:20, sep = "_") 
names(after_treatment) <- paste("Subject", 1:20, sep = "_") 

change <- after_treatment - pre_treatment 
average <- sum(change)/20
names(change)[change < 0]
names(change[which(change < 0)])
positivechange <- change[change < 0]
avg_positive <- mean(positivechange)

```
average decrease in blood pressure across all patients is 17
Except for "Subject_9"  "Subject_13" "Subject_17" experienced a decrease in blood pressure after treatment (a positive change)

# Task 2 
```{r}
# 2.1 
patient <- names(pre_treatment)
pre_bp <- pre_treatment
post_bp <- after_treatment
diff_bp <- change
df <- data.frame(patient, pre_bp, post_bp, diff_bp)
# 2.2 
subset(ds, diff_bp < 0)
# 2.3 
df$lessthan120 <- df$post_bp < 120 
# 2.4 
knitr::kable(df)
```

# Task 3 
```{r}
# 3.1. create a data frame for placebo group
placebo_pre <- c(138, 135, 147, 117, 152, 134, 114, 121, 131, 130)
placebo_pro <- c(105, 136, 123, 130, 134, 143, 135, 139, 120, 124)
placebo_df <- data.frame (placebo_pre, placebo_pro)
placebo_df$lessthan120 <- placebo_df$placebo_pro < 120

# 3.2 Create a list 
listexperiment <- list(treatment = df, placebo = placebo_df) 

# 3.3 three syntax 
listexperiment[1]
listexperiment$treatment
listexperiment[[1]]


```

# Task 4 
``` {r}
# 1. 
listexperiment$treatment$status <- character(20)
listexperiment$placebo$status <- character(10)

# 2. 
if df$post_bp <= 130 {{
  if df$post_bp <= 120 {
    then df$status <- optimal}
  else {df$status <- boarderline}}
else {df$status <- high}
  
  for (i=1:20) {
    if (listexperiment$treatment$post_bp[i] <= 120) listexperiment$treatment$status[i] = "optimal"
    if (listexperiment$treatment$post_bp > 120 and listexperiment$treatment$post_bp <= 130)
  listexperiment$treatment$status = "Bounderline"
    listexperiment$treatment$post_bp > 130)
    listexperiment$treatment$status = "high"}
  
    for (i=1:10) {
    if (listexperiment$placebo$post_bp <= 120) listexperiment$placebo$status = "optimal"
    if (listexperiment$placebo$post_bp > 120 and listexperiment$placebo$post_bp <= 130)
  listexperiment$placebo$status = "Bounderline"
    listexperiment$placebo$post_bp > 130)
    listexperiment$placebo$status = "high"}
  
  
    
    for (i in 1:5){
  if (i == 3) break #can put code to execute on the same line
  print(paste0("The ", words[i], " data point is ", data[i], "."))
}
    
    

```