---
title: "Ryan's HW2"
format: html
editor: visual
---
## Task 1: Basic Vector practice

1. 
```{r}
# Pre-treatment vector
pre <- c(130, 128, 116, 124, 133, 134, 118, 126, 114, 127,
         141, 138, 128, 140, 137, 131, 120, 128, 139, 135)
#Post-treatment vector
post <- c(114, 98, 113, 99, 107, 116, 113, 111, 119, 117,
          101, 119, 130, 122, 106, 106, 124, 102, 117, 113)

```

2.
```{r}
# Subject name labels
subject_names <- paste("Subject", 1:20, sep = "_")
subject_names
# Assigning names
names(pre) <- subject_names
names(post) <- subject_names
```

3.
```{r}
# Change in blood pressure
change <- pre - post
change
```

4.
```{r}
# Average decrease in blood pressure
mean(change)
```

5.
```{r}
# Which patients had a positive change
which(change > 0)
```
We can see that subjects number 9, 13, and 17 are missing because they did not have a positive change in blood pressure (i.e. their blood pressures went up).

6.
```{r}
# Subsetting vector of only positive change subjects
positive_change <- change[change > 0]
positive_change
```

7.
```{r}
mean(positive_change)
```

## Task 2: Basic Data Frame practice

1.
```{r}
# Data frame of task 1 data
bp_df <- data.frame(
  patient = subject_names,
  pre_bp = pre,
  post_bp = post,
  diff_bp = change
)
bp_df
```

2.
```{r}
# Only rows where diff_bp is negative
bp_df[bp_df$diff_bp < 0, ]
```
As we saw before, this subset only includes subjects 9, 13, and 17.

3.
```{r}
# New column: TRUE if post_bp<120
bp_df$under_120 <- bp_df$post_bp < 120
bp_df
```

4.
```{r}
# Print data frame
knitr::kable(bp_df)
```

## Task 3: List practice

1.
```{r}
# Placebo treatment data
pre_placebo <- c(138, 135, 147, 117, 152, 134, 114, 121, 131, 130)
post_placebo <- c(105, 136, 123, 130, 134, 143, 135, 139, 120, 124)

# Assigning subjects
placebo_names <- paste("Subject", 1:10, sep = "_")

# Taking difference
diff_placebo <- pre_placebo - post_placebo

# Placebo data frame
placebo_df <- data.frame(
  patient = placebo_names,
  pre_bp = pre_placebo,
  post_bp = post_placebo,
  diff_bp = diff_placebo
)

# Adding column: TRUE if post_bp<120
placebo_df$under_120 <- placebo_df$post_bp < 120
placebo_df

```

2.
```{r}
# List containing the two data frames
experiment_list <- list(
  treatment = bp_df,
  placebo = placebo_df
)

experiment_list
```

3.
```{r}
# Accessing the first element in three different ways
experiment_list$treatment

experiment_list[["treatment"]]

experiment_list[[1]]
```

4.
```{r}
# Accessing placebo df, pre_bp col
experiment_list$placebo$pre_bp
```

## Task 4: Control Flow Practice

1.

2.

3.

