<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ryan’s HW5</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-45431c2918bd31147ddb3fa7038bb99f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ryan’s HW5</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="task-1-querying-an-api-and-a-tidy-style-function" class="level2">
<h2 class="anchored" data-anchor-id="task-1-querying-an-api-and-a-tidy-style-function">Task 1: Querying an API and a Tidy-Style Function</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normally we would use gitignore to hide this</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>myKeyGoesHere <span class="ot">&lt;-</span> <span class="st">"26dc28fdf1374e47b762eb5b27036960"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We connect to newsapi.org for recent news.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Establishing present date - avoiding 30-day limitations of free account with newsapi</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>from_date <span class="ot">&lt;-</span> <span class="fu">Sys.Date</span>() <span class="sc">-</span> <span class="dv">30</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Grabbin recent news on the weather</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>news_result <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="fu">paste0</span>(</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://newsapi.org/v2/everything?"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"q=weather&amp;"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"from="</span>, from_date, <span class="st">"&amp;"</span>,  <span class="co"># This checks 30 days in the past from present</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"language=en&amp;"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pageSize=50&amp;"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"apiKey="</span>, myKeyGoesHere</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Using this result we parse it for the content.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()  masks stats::filter()
✖ purrr::flatten() masks jsonlite::flatten()
✖ dplyr::lag()     masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parse</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>parsed <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(news_result<span class="sc">$</span>content))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Storing as tibble</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>articles <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(parsed<span class="sc">$</span>articles)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>articles</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 44 × 8
   source$id $name author title description url   urlToImage publishedAt content
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;  
 1 the-verge The … Justi… Goog… "Google is… http… https://p… 2026-09-03… "&lt;ul&gt;&lt;…
 2 wired     Wired Kat M… The … "I found d… http… https://m… 2026-08-25… "Night…
 3 bbc-news  BBC … Steph… Lawr… "Dan Lawre… http… https://i… 2026-08-29… "Secon…
 4 bbc-news  BBC … Tomas… Yell… "The Met O… http… https://i… 2026-08-25… "Yello…
 5 &lt;NA&gt;      Gizm… Matth… Reco… "Built off… http… https://g… 2026-08-27… "Three…
 6 &lt;NA&gt;      Gizm… Bruce… Goog… "The tech … http… https://g… 2026-09-03… "In th…
 7 &lt;NA&gt;      Gizm… Matth… Scie… "Synergy b… http… https://g… 2026-09-14… "Somet…
 8 bbc-news  BBC … Sarah… Warm… "A stronge… http… https://i… 2026-09-14… "Forec…
 9 bbc-news  BBC … Ben R… Is a… "Temperatu… http… https://i… 2026-09-11… "Compu…
10 the-verge The … Justi… Bein… "It's 8:52… http… https://p… 2026-08-26… "&lt;ul&gt;&lt;…
# ℹ 34 more rows</code></pre>
</div>
</div>
<p>Below is a function for a user to query these results</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>query_news <span class="ot">&lt;-</span> <span class="cf">function</span>(search_term, from_date, api_key) {</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    result <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="fu">paste0</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://newsapi.org/v2/everything?"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"q="</span>, search_term, <span class="st">"&amp;"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"from="</span>, from_date, <span class="st">"&amp;"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"language=en&amp;"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"pageSize=50&amp;"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"apiKey="</span>, api_key</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  parsed <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(result<span class="sc">$</span>content))  <span class="co"># Parsing as before</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  articles <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(parsed<span class="sc">$</span>articles)  <span class="co"># Tibble as before</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(articles)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We define two queries to test the function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>query1 <span class="ot">&lt;-</span> <span class="fu">query_news</span>(<span class="st">"weather"</span>, <span class="fu">as.character</span>(<span class="fu">Sys.Date</span>() <span class="sc">-</span> <span class="dv">30</span>), myKeyGoesHere)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>query2 <span class="ot">&lt;-</span> <span class="fu">query_news</span>(<span class="st">"sports"</span>, <span class="fu">as.character</span>(<span class="fu">Sys.Date</span>() <span class="sc">-</span> <span class="dv">30</span>), myKeyGoesHere)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>And here are the results of the queries.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First query about weather</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>query1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 44 × 8
   source$id $name author title description url   urlToImage publishedAt content
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;  
 1 the-verge The … Justi… Goog… "Google is… http… https://p… 2026-09-03… "&lt;ul&gt;&lt;…
 2 wired     Wired Kat M… The … "I found d… http… https://m… 2026-08-25… "Night…
 3 bbc-news  BBC … Steph… Lawr… "Dan Lawre… http… https://i… 2026-08-29… "Secon…
 4 bbc-news  BBC … Tomas… Yell… "The Met O… http… https://i… 2026-08-25… "Yello…
 5 &lt;NA&gt;      Gizm… Matth… Reco… "Built off… http… https://g… 2026-08-27… "Three…
 6 &lt;NA&gt;      Gizm… Bruce… Goog… "The tech … http… https://g… 2026-09-03… "In th…
 7 &lt;NA&gt;      Gizm… Matth… Scie… "Synergy b… http… https://g… 2026-09-14… "Somet…
 8 bbc-news  BBC … Sarah… Warm… "A stronge… http… https://i… 2026-09-14… "Forec…
 9 bbc-news  BBC … Ben R… Is a… "Temperatu… http… https://i… 2026-09-11… "Compu…
10 the-verge The … Justi… Bein… "It's 8:52… http… https://p… 2026-08-26… "&lt;ul&gt;&lt;…
# ℹ 34 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Second query about sports</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>query2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 41 × 8
   source$id $name author title description url   urlToImage publishedAt content
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;  
 1 the-verge The … Terre… Fant… "Andy Holl… http… https://p… 2026-09-04… "&lt;ul&gt;&lt;…
 2 the-verge The … Emma … ESPN… "ESPN is h… http… https://p… 2026-08-24… "&lt;ul&gt;&lt;…
 3 bbc-news  BBC … https… The … "Several p… http… https://i… 2026-09-14… "Image…
 4 bbc-news  BBC … https… Week… "How much … http… https://i… 2026-09-17… "This …
 5 bbc-news  BBC … Ben C… Why … "The NFL h… http… https://i… 2026-09-10… "Live …
 6 &lt;NA&gt;      CNET  Corin… Behi… "How are t… http… https://w… 2026-08-24… "When …
 7 business… Busi… Susan… I ra… "I raised … http… https://i… 2026-08-26… "The a…
 8 business… Busi… Allie… Mamd… "Zohran Ma… http… https://i… 2026-08-25… "New Y…
 9 &lt;NA&gt;      CNET  Ty Pe… Sony… "Sony’s ad… http… https://w… 2026-08-31… "Seven…
10 bbc-news  BBC … Dale … Was … "Was Gary … http… https://i… 2026-09-21… "\"Whe…
# ℹ 31 more rows</code></pre>
</div>
</div>
</section>
<section id="task-2-summarizing-roller-coaster-data" class="level2">
<h2 class="anchored" data-anchor-id="task-2-summarizing-roller-coaster-data">Task 2: Summarizing Roller Coaster Data</h2>
<p>We move on to examining roller coaster data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in roller coaster data</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>rc_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/online/datasets/635USrollercoasters.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 635 Columns: 21
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (12): Coaster, Park, City, State, Census Region, AgeGroup, Scale, Type, ...
dbl  (9): Year Opened, TopSpeed, MaxHeight, Drop, Length, Duration, # of Inv...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking structure</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rc_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [635 × 21] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Coaster        : chr [1:635] "Adrenaline Peak" "Adventure Express" "Afterburn" "Aftershock" ...
 $ Park           : chr [1:635] "Oaks Amusement Park" "Kings Island" "Carowinds" "Silverwood Theme Park" ...
 $ City           : chr [1:635] "Portland" "Mason" "Charlotte" "Athol" ...
 $ State          : chr [1:635] "Oregon" "Ohio" "North Carolina" "Idaho" ...
 $ Census Region  : chr [1:635] "West" "Midwest" "South" "West" ...
 $ Year Opened    : num [1:635] 2018 1991 1999 2008 2010 ...
 $ AgeGroup       : chr [1:635] "3:Newest" "2:Recent" "2:Recent" "3:Newest" ...
 $ TopSpeed       : num [1:635] 45 35 62 65.6 22 67 35 66 48 50 ...
 $ MaxHeight      : num [1:635] 72 63 113 192 25 ...
 $ Scale          : chr [1:635] "Extreme" "Thrill" "Extreme" "Extreme" ...
 $ Type           : chr [1:635] "Steel" "Steel" "Steel" "Steel" ...
 $ Design         : chr [1:635] "Sit Down" "Sit Down" "Inverted" "Inverted" ...
 $ Drop           : num [1:635] 70 47 110 177 22.5 170 20 147 80 144 ...
 $ Length         : num [1:635] 1050 2963 2956 1204 628 ...
 $ Duration       : num [1:635] 66 140 167 92 47 190 100 143 110 110 ...
 $ Inversions?    : chr [1:635] "Yes" "No" "Yes" "Yes" ...
 $ # of Inversions: num [1:635] 3 0 6 3 0 6 0 0 0 4 ...
 $ Make           : chr [1:635] "Gerstlauer Amusement Rides GmbH" "Arrow Dynamics" "Bolliger &amp; Mabillard" "Vekoma" ...
 $ Latitude       : num [1:635] 45.5 39.4 35.3 47.9 28 ...
 $ Longitude      : num [1:635] -122.7 -84.3 -80.8 -116.7 -82.6 ...
 $ Boundary       : chr [1:635] "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":95988.013,\"NAME\":\"Oregon\",\"GEO_ID\":\"0400000US41\",\"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":40860.694,\"NAME\":\"Ohio\",\"GEO_ID\":\"0400000US39\",\"L"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":48617.905,\"NAME\":\"North Carolina\",\"GEO_ID\":\"0400000"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":82643.117,\"NAME\":\"Idaho\",\"GEO_ID\":\"0400000US16\",\""| __truncated__ ...
 - attr(*, "spec")=
  .. cols(
  ..   Coaster = col_character(),
  ..   Park = col_character(),
  ..   City = col_character(),
  ..   State = col_character(),
  ..   `Census Region` = col_character(),
  ..   `Year Opened` = col_double(),
  ..   AgeGroup = col_character(),
  ..   TopSpeed = col_double(),
  ..   MaxHeight = col_double(),
  ..   Scale = col_character(),
  ..   Type = col_character(),
  ..   Design = col_character(),
  ..   Drop = col_double(),
  ..   Length = col_double(),
  ..   Duration = col_double(),
  ..   `Inversions?` = col_character(),
  ..   `# of Inversions` = col_double(),
  ..   Make = col_character(),
  ..   Latitude = col_double(),
  ..   Longitude = col_double(),
  ..   Boundary = col_character()
  .. )
 - attr(*, "problems")=&lt;pointer: 0x7fdf9facad60&gt; </code></pre>
</div>
</div>
<section id="basic-eda" class="level3">
<h3 class="anchored" data-anchor-id="basic-eda">Basic EDA</h3>
<p>From the above structure of the roller coaster data, we observe that many categorical variables (e.g <span class="math inline">\(\texttt{Scale}\)</span>, <span class="math inline">\(\texttt{Census Region}\)</span>, etc) are read in as strings. These would likely benefit from being converted to factors. Furthermore, multiple variables contain spaces (e.g.&nbsp;<span class="math inline">\(\texttt{Census Region}\)</span>) or special characters (e.g <span class="math inline">\(\texttt{Inversions?}\)</span>) that we shall want to deal with using backticks.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert AgeGroup to ordered factor</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>rc_data<span class="sc">$</span>AgeGroup <span class="ot">&lt;-</span> <span class="fu">factor</span>(rc_data<span class="sc">$</span>AgeGroup,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1:Older"</span>, <span class="st">"2:Recent"</span>, <span class="st">"3:Newest"</span>),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert other variables to factor and dealing with spaces and special chars</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>rc_data<span class="sc">$</span>Scale <span class="ot">&lt;-</span> <span class="fu">factor</span>(rc_data<span class="sc">$</span>Scale)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>rc_data<span class="sc">$</span>Type <span class="ot">&lt;-</span> <span class="fu">factor</span>(rc_data<span class="sc">$</span>Type)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>rc_data<span class="sc">$</span>Design <span class="ot">&lt;-</span> <span class="fu">factor</span>(rc_data<span class="sc">$</span>Design)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>rc_data<span class="sc">$</span><span class="st">`</span><span class="at">Census Region</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">factor</span>(rc_data<span class="sc">$</span><span class="st">`</span><span class="at">Census Region</span><span class="st">`</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>rc_data<span class="sc">$</span><span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">factor</span>(rc_data<span class="sc">$</span><span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-check structure, check summary, and missing values</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rc_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [635 × 21] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Coaster        : chr [1:635] "Adrenaline Peak" "Adventure Express" "Afterburn" "Aftershock" ...
 $ Park           : chr [1:635] "Oaks Amusement Park" "Kings Island" "Carowinds" "Silverwood Theme Park" ...
 $ City           : chr [1:635] "Portland" "Mason" "Charlotte" "Athol" ...
 $ State          : chr [1:635] "Oregon" "Ohio" "North Carolina" "Idaho" ...
 $ Census Region  : Factor w/ 4 levels "Midwest","Northeast",..: 4 1 3 4 3 3 2 1 1 3 ...
 $ Year Opened    : num [1:635] 2018 1991 1999 2008 2010 ...
 $ AgeGroup       : Ord.factor w/ 3 levels "1:Older"&lt;"2:Recent"&lt;..: 3 2 2 3 3 2 2 2 3 2 ...
 $ TopSpeed       : num [1:635] 45 35 62 65.6 22 67 35 66 48 50 ...
 $ MaxHeight      : num [1:635] 72 63 113 192 25 ...
 $ Scale          : Factor w/ 4 levels "Extreme","Family",..: 1 4 1 1 2 1 4 1 4 1 ...
 $ Type           : Factor w/ 2 levels "Steel","Wood": 1 1 1 1 1 1 1 2 2 1 ...
 $ Design         : Factor w/ 7 levels "Bobsled","Flying",..: 4 4 3 3 4 3 1 4 4 4 ...
 $ Drop           : num [1:635] 70 47 110 177 22.5 170 20 147 80 144 ...
 $ Length         : num [1:635] 1050 2963 2956 1204 628 ...
 $ Duration       : num [1:635] 66 140 167 92 47 190 100 143 110 110 ...
 $ Inversions?    : Factor w/ 2 levels "No","Yes": 2 1 2 2 1 2 1 1 1 2 ...
 $ # of Inversions: num [1:635] 3 0 6 3 0 6 0 0 0 4 ...
 $ Make           : chr [1:635] "Gerstlauer Amusement Rides GmbH" "Arrow Dynamics" "Bolliger &amp; Mabillard" "Vekoma" ...
 $ Latitude       : num [1:635] 45.5 39.4 35.3 47.9 28 ...
 $ Longitude      : num [1:635] -122.7 -84.3 -80.8 -116.7 -82.6 ...
 $ Boundary       : chr [1:635] "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":95988.013,\"NAME\":\"Oregon\",\"GEO_ID\":\"0400000US41\",\"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":40860.694,\"NAME\":\"Ohio\",\"GEO_ID\":\"0400000US39\",\"L"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":48617.905,\"NAME\":\"North Carolina\",\"GEO_ID\":\"0400000"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":82643.117,\"NAME\":\"Idaho\",\"GEO_ID\":\"0400000US16\",\""| __truncated__ ...
 - attr(*, "spec")=
  .. cols(
  ..   Coaster = col_character(),
  ..   Park = col_character(),
  ..   City = col_character(),
  ..   State = col_character(),
  ..   `Census Region` = col_character(),
  ..   `Year Opened` = col_double(),
  ..   AgeGroup = col_character(),
  ..   TopSpeed = col_double(),
  ..   MaxHeight = col_double(),
  ..   Scale = col_character(),
  ..   Type = col_character(),
  ..   Design = col_character(),
  ..   Drop = col_double(),
  ..   Length = col_double(),
  ..   Duration = col_double(),
  ..   `Inversions?` = col_character(),
  ..   `# of Inversions` = col_double(),
  ..   Make = col_character(),
  ..   Latitude = col_double(),
  ..   Longitude = col_double(),
  ..   Boundary = col_character()
  .. )
 - attr(*, "problems")=&lt;pointer: 0x7fdf9facad60&gt; </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rc_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Coaster           Park            City           State    
 Length   :635   Length   :635   Length   :635   Length   :635  
 N.unique :482   N.unique :197   N.unique :171   N.unique : 40  
 N.blank  :  0   N.blank  :  0   N.blank  :  0   N.blank  :  0  
 Min.nchar:  2   Min.nchar:  6   Min.nchar:  3   Min.nchar:  4  
 Max.nchar: 46   Max.nchar: 47   Max.nchar: 20   Max.nchar: 14  
                                                                
                                                                
   Census Region  Year Opened       AgeGroup      TopSpeed        MaxHeight    
 Midwest  :134   Min.   :1920   1:Older : 69   Min.   :  6.00   Min.   :  5.0  
 Northeast:156   1st Qu.:1995   2:Recent:190   1st Qu.: 28.50   1st Qu.: 28.0  
 South    :223   Median :2002   3:Newest:376   Median : 45.00   Median : 64.3  
 West     :122   Mean   :1999                  Mean   : 42.24   Mean   : 76.8  
                 3rd Qu.:2013                  3rd Qu.: 55.00   3rd Qu.:109.0  
                 Max.   :2020                  Max.   :128.00   Max.   :456.0  
                                               NAs    :74       NAs    :8      
     Scale        Type           Design         Drop            Length    
 Extreme:269   Steel:530   Bobsled  :  4   Min.   :  0.00   Min.   :  48  
 Family :178   Wood :105   Flying   :  9   1st Qu.: 25.00   1st Qu.: 900  
 Kiddie : 28               Inverted : 42   Median : 70.00   Median :1490  
 Thrill :160               Sit Down :560   Mean   : 77.18   Mean   :1938  
                           Stand Up :  4   3rd Qu.:108.50   3rd Qu.:2800  
                           Suspended:  7   Max.   :418.00   Max.   :7359  
                           Wing     :  9   NAs    :128      NAs    :33    
    Duration   Inversions? # of Inversions         Make        Latitude    
 Min.   : 20   No :465     Min.   :0.0000   Length   :635   Min.   :26.55  
 1st Qu.: 70   Yes:170     1st Qu.:0.0000   N.unique : 53   1st Qu.:34.47  
 Median :101               Median :0.0000   N.blank  :  0   Median :38.51  
 Mean   :106               Mean   :0.9213   Min.nchar:  4   Mean   :37.69  
 3rd Qu.:130               3rd Qu.:1.0000   Max.nchar: 36   3rd Qu.:40.97  
 Max.   :540               Max.   :8.0000   NAs      : 36   Max.   :47.92  
 NAs    :66                                                                
   Longitude            Boundary    
 Min.   :-122.94   Length   :  635  
 1st Qu.: -97.15   N.unique :   41  
 Median : -84.31   N.blank  :    0  
 Mean   : -89.46   Min.nchar: 6568  
 3rd Qu.: -77.46   Max.nchar:32759  
 Max.   : -70.39                    
                                    </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(rc_data))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Coaster            Park            City           State   Census Region 
              0               0               0               0               0 
    Year Opened        AgeGroup        TopSpeed       MaxHeight           Scale 
              0               0              74               8               0 
           Type          Design            Drop          Length        Duration 
              0               0             128              33              66 
    Inversions? # of Inversions            Make        Latitude       Longitude 
              0               0              36               0               0 
       Boundary 
              0 </code></pre>
</div>
</div>
<p>Here are some observations after these changes: - Unlike the what instructions indicate, <span class="math inline">\(\texttt{Scale}\)</span> appears to have 4 levels, not 3. The fourth factor being “Kiddie” - Six columns have missing values: <span class="math inline">\(\texttt{TopSpeed}, \texttt{MaxHeight}, \texttt{Drop}, \texttt{Length}, \texttt{Duration}, \texttt{Make}\)</span>. None of these are the variables we converted to factor.</p>
</section>
<section id="categorical-variables" class="level3">
<h3 class="anchored" data-anchor-id="categorical-variables">Categorical variables</h3>
<p>Next we will start making tables from these data, beginning with a one-, two-, and three-way contingency table. We will build the first with the <span class="math inline">\(\texttt{Type}\)</span> variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way: Type</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>one_way <span class="ot">&lt;-</span> <span class="fu">table</span>(rc_data<span class="sc">$</span>Type)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>one_way</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Steel  Wood 
  530   105 </code></pre>
</div>
</div>
<p>In the one-way table we observe 530 steel types from the total of 530 + 105 = 605 roller coasters. So a sizable majority of roller coasters are made from steel, as opposed to wood.</p>
<p>Next we’ll make a two-way table from <span class="math inline">\(\texttt{Type}\)</span> and <span class="math inline">\(\texttt{Scale}\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-way: Type by Scale</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>two_way <span class="ot">&lt;-</span> <span class="fu">table</span>(rc_data<span class="sc">$</span>Type, rc_data<span class="sc">$</span>Scale)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>two_way</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        Extreme Family Kiddie Thrill
  Steel     216    163     27    124
  Wood       53     15      1     36</code></pre>
</div>
</div>
<p>Let’s inspect the <code>15</code> value. That means that 15 of the 105 wood roller coasters were classified as “Family” roller coasters. This the third most common type of ride for wood roller coasters, while the family steel coaster was the second most common within steel.</p>
<p>Next we’ll make a three-way table from <span class="math inline">\(\texttt{Type}\)</span>, <span class="math inline">\(\texttt{Scale}\)</span> and <span class="math inline">\(\texttt{Census Region}\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three-way: Type by Scale by Census Region</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>three_way <span class="ot">&lt;-</span> <span class="fu">table</span>(rc_data<span class="sc">$</span>Type, rc_data<span class="sc">$</span>Scale, rc_data<span class="sc">$</span><span class="st">`</span><span class="at">Census Region</span><span class="st">`</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>three_way</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>, ,  = Midwest

       
        Extreme Family Kiddie Thrill
  Steel      42     26      8     24
  Wood       19      6      0      9

, ,  = Northeast

       
        Extreme Family Kiddie Thrill
  Steel      50     43      6     27
  Wood       12      6      1     11

, ,  = South

       
        Extreme Family Kiddie Thrill
  Steel      79     65      6     46
  Wood       13      3      0     11

, ,  = West

       
        Extreme Family Kiddie Thrill
  Steel      45     29      7     27
  Wood        9      0      0      5</code></pre>
</div>
</div>
<p>Let’s hone in on the West region, Wood coaster, classified as Family. This has 0 recorded observations, which means there are no wooden family coasters in the Western region. Contrast that with the respective wood-family coasters in other regions, we see that the other regions all have non-zero values. This makes the West unique on this particular coaster, suggesting that the West could be less family-oriented in terms of roller coaster attractions. This seems to hold when accounting for total numbers of family coasters (including steel), although steel coasters do exist for this purpose in the West.</p>
<p>Now we will create a conditional two-way table in two different ways. We will condition on <span class="math inline">\(\texttt{Census Region = South}\)</span>, then use variables <span class="math inline">\(\texttt{Type}\)</span> and <span class="math inline">\(\texttt{Scale}\)</span> for the two-way. The first method will subset at the beginning of the process.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>south_data <span class="ot">&lt;-</span> <span class="fu">filter</span>(rc_data, <span class="st">`</span><span class="at">Census Region</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"South"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>south_two_way <span class="ot">&lt;-</span> <span class="fu">table</span>(south_data<span class="sc">$</span>Type, south_data<span class="sc">$</span>Scale)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>south_two_way</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        Extreme Family Kiddie Thrill
  Steel      79     65      6     46
  Wood       13      3      0     11</code></pre>
</div>
</div>
<p>The second method will create a three-way table first then subset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>south_two_way2 <span class="ot">&lt;-</span> three_way[, , <span class="st">"South"</span>] <span class="co"># This calls the table from the prior question built from the same variables</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>south_two_way2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        Extreme Family Kiddie Thrill
  Steel      79     65      6     46
  Wood       13      3      0     11</code></pre>
</div>
</div>
<p>Next we recreate the two-way contingency table of <span class="math inline">\(\texttt{Type}\)</span> and <span class="math inline">\(\texttt{Scale}\)</span> from earlier using dplyr functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>type_scale_2way <span class="ot">&lt;-</span> rc_data <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Type, Scale) <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Scale, <span class="at">values_from =</span> count) <span class="co"># Making output look more like a table() function</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has regrouped the output.
ℹ Summaries were computed grouped by Type and Scale.
ℹ Output is grouped by Type.
ℹ Use `summarise(.groups = "drop_last")` to silence this message.
ℹ Use `summarise(.by = c(Type, Scale))` for per-operation grouping
  (`?dplyr::dplyr_by`) instead.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>type_scale_2way</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
# Groups:   Type [2]
  Type  Extreme Family Kiddie Thrill
  &lt;fct&gt;   &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;
1 Steel     216    163     27    124
2 Wood       53     15      1     36</code></pre>
</div>
</div>
<p>Lastly, we shall plot a stacked and side-by-side bar graph. Since the tibble above is a bit harder to use than it’s table() version from earlier, we will opt to use the <code>two_way</code> table we established.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to df</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>type_scale_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(two_way)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Stacked bar graph</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> type_scale_df, <span class="fu">aes</span>(<span class="at">x =</span> Var1, <span class="at">y =</span> Freq, <span class="at">fill =</span> Var2)) <span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Coaster Type"</span>,</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Coasters"</span>,</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Roller Coaster Scale by Type"</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">+</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Scale"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="RyanHW5_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Side-by-side bar graph</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> type_scale_df, <span class="fu">aes</span>(<span class="at">x =</span> Var1, <span class="at">y =</span> Freq, <span class="at">fill =</span> Var2)) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Coaster Type"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Coasters"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Roller Coaster Scale by Type"</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Scale"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="RyanHW5_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>